openapi: "3.1.0"
info:
  title: "Forms API"
  version: "1.0.0"
servers:
  - url: "/v1"
paths: {}
components:
  schemas:
    Submission:
      type: "object"
      properties:
        submission:
          type: "string"
          description: "The form submission"
