title: GC Forms API Documentation
description: This documentation is for developers who want to use the GC Forms API to retrieve form submission data programmatically into their department’s web application or back-office system. 
theme: jekyll-theme-minimal


# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: GC Forms API Documentation
subtitle: How to retrieve form submissions from an API endpoint

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/api-documentation'

# Author/Organization info to be displayed in the templates
author:
  name: Canadian Digital Service
  url: https://digital.canada.ca

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: forms-api
  description: GC Forms API
  url: https://github.com/cds-snc/forms-api


# Style Variables
brand_color: "#FFCC3D"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
