# Site settings
title: GC Forms API
repository: cds-snc/forms-api
description: >-
 This documentation site is for developers who want to use the GC Forms API to retrieve form submission data programmatically into their department’s web application or back-office system. 

# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown, GFM
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/
  
# Theme
theme: jekyll-theme-gcweb

#Plugins
plugins:
- jekyll-coffeescript
- jekyll-commonmark-ghpages
- jekyll-default-layout
- jekyll-gfm-admonitions
- jekyll-gist
- jekyll-github-metadata
- jekyll-optional-front-matter
- jekyll-paginate
- jekyll-readme-index
- jekyll-remote-theme
- jekyll-relative-links
- jekyll-titles-from-headings
- jekyll-relative-links
- jekyll-seo-tag
- kramdown-parser-gfm 

# Title
name: GC Forms API
subtitle: This documentation is for developers who want to use the GC Forms API to retrieve form submission data programmatically into their department’s web application or back-office system. 

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/forms-api'

# Author/Organization info to be displayed in the templates
author:
  name: GC Forms
  url: https://articles.alpha.canada.ca/forms-formulaires/
author2:
  name: Canadian Digital Service
  url: https://digital.canada.ca

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name:
  description:
  url:

# Style Variables
brand_color: "#4b4085ff"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
