name: "Deploy documentation"

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.x

      - name: Install MkDocs Material
        run: |
          pip install mkdocs-material mkdocs-static-i18n[material] mkdocs-open-in-new-tab

      - name: Push documentation to gh-pages branch
        working-directory: documentation
        run: mkdocs gh-deploy
