name: "Deploy documentation"

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs Material
        run: |
          pip install mkdocs-material mkdocs-static-i18n[material] mkdocs-open-in-new-tab

      - name: Push documentation to gh-pages branch
        working-directory: documentation
        run: mkdocs gh-deploy
