name: "Production — Docker build and push"

on:
  release:
    types: [published]

env:
  AWS_ACCOUNT_ID: ${{ vars.PRODUCTION_AWS_ACCOUNT_ID }}
  AWS_REGION: ca-central-1
  ECR_REPOSITORY: forms/api
  TAG_VERSION: ${{ github.ref_name }}

permissions:
  id-token: write
  contents: write
  security-events: write

jobs:
  push-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build Docker image
        run: docker build -t forms/api .

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/forms-api-release
          role-session-name: ECRPush
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@27f0358e4101cb57222f3a355e6c80008b3c6ffc

      - name: Tag images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag forms/api $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_VERSION
          docker tag forms/api $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Push images to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_VERSION
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Docker generate SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@34794baf2af592913bb5b51d8df4f8d0acc49b6f # v3.2.0
        env:
          TRIVY_DB_REPOSITORY: ${{ vars.TRIVY_DB_REPOSITORY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          docker_image: "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.TAG_VERSION }}"
          dockerfile_path: "Dockerfile"
          sbom_name: "forms-api"
          token: "${{ secrets.GITHUB_TOKEN }}"
