name: "Production — Docker build and push"

on:
  release:
    types: [published]

env:
  AWS_ACCOUNT_ID: ${{ vars.PRODUCTION_AWS_ACCOUNT_ID }}
  AWS_REGION: ca-central-1
  ECR_REPOSITORY: forms/api
  TAG_VERSION: ${{ github.ref_name }}

permissions:
  id-token: write
  contents: write
  security-events: write

jobs:
  push-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build Docker image
        run: docker build -t forms/api .

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/forms-api-release
          role-session-name: ECRPush
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@08fda13c2502925256496fadb53b7718f48b28c5

      - name: Tag images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag forms/api $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_VERSION
          docker tag forms/api $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Push images to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_VERSION
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Docker generate SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@598deeaed48ab3bb0df85f0ed124ba53f0ade385 # v3.1.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          docker_image: "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.TAG_VERSION }}"
          dockerfile_path: "Dockerfile"
          sbom_name: "forms-api"
          token: "${{ secrets.GITHUB_TOKEN }}"
